version: '3.8'

services:
  api-prod:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
  api-dev:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
